### ISSUE TITLE
Unhandled event: [u'error', u'You are temporarily banned.']

### ISSUE THREAD

**Issue by RiotD3v** [elias94/pyomegle#6] opened 2019-11-16 15:40 UTC
I keep getting an error Unhandled event: [u'error', u'You are temporarily banned.']
Although I don't believe I am actually banned, I can acceess omegle through my browser and there are no issues.

```python
from pyomegle import OmegleClient
from pyomegle import OmegleHandler
import time

h = OmegleHandler(loop=True)
c = OmegleClient(h, wpm=47, lang="en")
c.start()

input_str = "message"

while 1:
    time.sleep(5)
    c.send(input_str)
    c.next()
```

**Comment by swartic** [comment] 2019-11-23 03:12
you need to do a captcha. try going to omegle.com, do the captcha, and then do this again

**Comment by RiotD3v** [comment] 2019-11-23 11:03
I already did the captcha on omegle multiple times and I still get the issue

**Comment by LordDraagonLive** [comment] 2020-07-03 03:48
I'm not sure if this will work but how about refreshing the bot and changing the geolocation

**Comment by danny-burrows** [comment] 2020-07-05 13:29
I believe this issue is caused by Omegle changing the way they have implemented recaptcha. They now require `caps=recaptcha2` to be present in the URL when requesting to start a chat. 

A really quick down and dirty fix for this could be to add this at the top of the script...
```python
from pyomegle import Omegle
Omegle.START_URL = Omegle.START_URL.replace("rcs=%s", "rcs=%s&caps=recaptcha2")
```

While this URL change does fix the temporarily banned messages there are also some other things to consider...

I would suggest doing what @LordDraagonLive says as Omegle seems to soft ban certain IP's by just sending an empty JSON response, this is what causes the "Error connecting to server" message on Omegle itself, and a `KeyError: 'clientID'` in pyomegle.

Also, if Omegle works out you might be a bot they will start asking for recaptchas for every /start request you send which effectivly just moves the problem from getting 'You are temporarily banned.' messages to 'Recaptcha required.' messages. 

As of yet I havent found a good fix for recaptchas other than using a VPN and not acting like a bot.

Hope this helps.

**Comment by FrostplayGames** [comment] 2020-09-01 13:49
Did you manage to fix this? I am having trouble with this too.

**Comment by eliascotto** [comment] 2020-10-26 00:31
@danny-burrows thanks for the update, if you are able to test if nothing is broken modifying `Omegle.START_URL` you can open a pull request and I will eventually merge it

**Closed as completed** 2021-01-10 23:51 UTC
